export const mapOverlays = {
    'CartoDB Positron' : 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
    'CartoDB Dark matter' : 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png',
    'CartoDB Positron (lite)' : 'https://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}.png',
    'CartoDB Dark matter (lite)' : 'https://{s}.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}.png',
    'CartoDB World Antique' : 'https://cartocdn_{s}.global.ssl.fastly.net/base-antique/{z}/{x}/{y}.png',
    'CartoDB World Eco' : 'https://cartocdn_{s}.global.ssl.fastly.net/base-eco/{z}/{x}/{y}.png',
    'CartoDB World Flat Blue' : 'https://cartocdn_{s}.global.ssl.fastly.net/base-flatblue/{z}/{x}/{y}.png',
    'CartoDB World Midnight Commander' : 'https://cartocdn_{s}.global.ssl.fastly.net/base-midnight/{z}/{x}/{y}.png',
    'Mapzen Terrain (AWS)' : 'https://s3.amazonaws.com/elevation-tiles-prod/normal/{z}/{x}/{y}.png',
    'Mapzen Terrarium (AWS)' : 'https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png',
    'OSM Open Street Map' : 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    'Stamen Terain' : 'https://stamen-tiles-{s}.a.ssl.fastly.net/terrain/{z}/{x}/{y}.png',
    'Stamen Terain Background' : 'https://stamen-tiles-{s}.a.ssl.fastly.net/terrain-background/{z}/{x}/{y}.png',
    'Stamen Toner' : 'https://stamen-tiles-{s}.a.ssl.fastly.net/toner/{z}/{x}/{y}.png',
    'Stamen Toner Background' : 'https://stamen-tiles-{s}.a.ssl.fastly.net/toner-background/{z}/{x}/{y}.png',
    'Stamen Toner Light' : 'https://stamen-tiles-{s}.a.ssl.fastly.net/toner-lite/{z}/{x}/{y}.png',
    'Stamen Watercolor' : 'https://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.png',
}
